Public Interface IMotor
    Sub EscriureParametreUnic(index As UInteger, value As Single)
    Sub EscriureParametreUnic(index As UInteger, value As Byte)
    Sub LlegirParametreUnic(index As UInteger)
    Sub DesactivarMotor()
    Sub ActivarMotor()
    Sub EstablirZeroMecanic()
    Sub EstablirModePosicio()
    Sub EstablirModeVelocitat()
    Sub EstablirVelocitat(value As Single)
    Sub EstablirLimitVelocitat(value As Single)
    Sub EstablirPosicio(value As Single)
    Sub EstablirIDDispositiu(MasterCANID As UInteger, NEWCANID As UInteger)
    Sub EstablirModeControl()
    Sub EnviarComandaControlMotor(torque As Single, target_angle As Single, target_velocity As Single, Kp As Single, Kd As Single)
End Interface
